- name: copy Mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

