- name: copy systemD file
  ansible.builtin.copy:
    src: "{{ componet }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: start {{ component }} service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon-reload: yes
